//! Out-of-band absolute numbers behind the shape claims (docs/design/morphe.md
//! §13). Run per milestone: `cargo bench -p morphe`. These prove wall-clock
//! magnitudes on one machine; they cannot prove complexity class — the in-gate
//! shape test (`tests/scaling_shape.rs`) holds that.

use criterion::Criterion;

use morphe::themelios_syntax::base::source::SourceId;
use morphe::themelios_syntax::parse::parse;
use morphe::{Dialect, FormatOptions, Parse, Program, Source, format, format_parsed};

/// One rule with a comment run, a pool, an interval, an aggregate, and a theory
/// atom — the same fixture the shape test uses, so every size exercises the
/// layout families the render walks (§7.2).
const UNIT: &str = "% leading\np(X, f(Y)) :- q(X; Y), not r(X), X = 1..3, #sum { W,T : t(T,W) } >= 4, &sum { x, -y : p } <= 3. % trailing\n";

fn admitted(units: usize) -> Source {
    Source::new(SourceId::new(0), UNIT.repeat(units)).expect("bench text admits")
}

fn parsed(units: usize) -> Parse<Program> {
    parse(&admitted(units), Dialect::Clingo)
}

/// `format` end to end — parse, lower, render, certify — over the input text.
fn formatting(c: &mut Criterion) {
    let options = FormatOptions::default();
    for units in [64usize, 1024, 8192] {
        let source = admitted(units);
        c.bench_function(&format!("format/{units}-rules"), |b| {
            b.iter(|| format(std::hint::black_box(&source), &options));
        });
    }
}

/// `format_parsed` — the layout pass and the certificate over a tree already
/// parsed, the input parse excluded.
fn layout(c: &mut Criterion) {
    let options = FormatOptions::default();
    for units in [64usize, 1024, 8192] {
        let parse = parsed(units);
        c.bench_function(&format!("format_parsed/{units}-rules"), |b| {
            b.iter(|| format_parsed(std::hint::black_box(&parse), &options));
        });
    }
}

// The harness, written out rather than generated by `criterion_group!` and
// `criterion_main!`: the macros expand to exactly this, and the generated group
// is a public function without documentation, which the workspace's denied
// `missing_docs` refuses. Same behavior, one documented item.

/// The scaling group: every bench above, under criterion's default
/// configuration as adjusted by the command line.
pub fn scaling() {
    let mut criterion: Criterion = Criterion::default().configure_from_args();
    formatting(&mut criterion);
    layout(&mut criterion);
}

fn main() {
    scaling();
    Criterion::default().configure_from_args().final_summary();
}
